//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace CoreComponent.ReportDataSet {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DistributorPanBankDetails")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DistributorPanBankDetails : global::System.Data.DataSet {
        
        private RptDistributorDetailDataTable tableRptDistributorDetail;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DistributorPanBankDetails() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DistributorPanBankDetails(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["RptDistributorDetail"] != null)) {
                    base.Tables.Add(new RptDistributorDetailDataTable(ds.Tables["RptDistributorDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RptDistributorDetailDataTable RptDistributorDetail {
            get {
                return this.tableRptDistributorDetail;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            DistributorPanBankDetails cln = ((DistributorPanBankDetails)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["RptDistributorDetail"] != null)) {
                    base.Tables.Add(new RptDistributorDetailDataTable(ds.Tables["RptDistributorDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRptDistributorDetail = ((RptDistributorDetailDataTable)(base.Tables["RptDistributorDetail"]));
            if ((initTable == true)) {
                if ((this.tableRptDistributorDetail != null)) {
                    this.tableRptDistributorDetail.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DistributorPanBankDetails";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DistributorPanBankDetails.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRptDistributorDetail = new RptDistributorDetailDataTable();
            base.Tables.Add(this.tableRptDistributorDetail);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeRptDistributorDetail() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DistributorPanBankDetails ds = new DistributorPanBankDetails();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void RptDistributorDetailRowChangeEventHandler(object sender, RptDistributorDetailRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class RptDistributorDetailDataTable : global::System.Data.TypedTableBase<RptDistributorDetailRow> {
            
            private global::System.Data.DataColumn columnDistributorId;
            
            private global::System.Data.DataColumn columnUplineDistributorId;
            
            private global::System.Data.DataColumn columnDistributorTitle;
            
            private global::System.Data.DataColumn columnDistributorDOB;
            
            private global::System.Data.DataColumn columnCo_DistributorTitle;
            
            private global::System.Data.DataColumn columnKeyValue11;
            
            private global::System.Data.DataColumn columnCo_DistributorFirstName;
            
            private global::System.Data.DataColumn columnCo_DistributorLastName;
            
            private global::System.Data.DataColumn columnCo_DistributorDOB;
            
            private global::System.Data.DataColumn columnDistributorAddress1;
            
            private global::System.Data.DataColumn columnDistributorAddress2;
            
            private global::System.Data.DataColumn columnDistributorAddress3;
            
            private global::System.Data.DataColumn columnDistributorAddress4;
            
            private global::System.Data.DataColumn columnDistributorCityCode;
            
            private global::System.Data.DataColumn columnCityName;
            
            private global::System.Data.DataColumn columnDistributorStateCode;
            
            private global::System.Data.DataColumn columnStateName;
            
            private global::System.Data.DataColumn columnDistributorCountryCode;
            
            private global::System.Data.DataColumn columnCountryName;
            
            private global::System.Data.DataColumn columnDistributorPinCode;
            
            private global::System.Data.DataColumn columnDistributorTeleNumber;
            
            private global::System.Data.DataColumn columnDistributorMobNumber;
            
            private global::System.Data.DataColumn columnDistributorFaxNumber;
            
            private global::System.Data.DataColumn columnDistributorEMailID;
            
            private global::System.Data.DataColumn columnDistributorPANNumber;
            
            private global::System.Data.DataColumn columnDistributorRegistrationDate;
            
            private global::System.Data.DataColumn columnDistributorBankBranch;
            
            private global::System.Data.DataColumn columnDistributorBankAccNumber;
            
            private global::System.Data.DataColumn columnDistributorBankName;
            
            private global::System.Data.DataColumn columnBankID;
            
            private global::System.Data.DataColumn columnBankName;
            
            private global::System.Data.DataColumn columnBranchName;
            
            private global::System.Data.DataColumn columnFullName;
            
            private global::System.Data.DataColumn columnSaveOn;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RptDistributorDetailDataTable() {
                this.TableName = "RptDistributorDetail";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RptDistributorDetailDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected RptDistributorDetailDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorIdColumn {
                get {
                    return this.columnDistributorId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UplineDistributorIdColumn {
                get {
                    return this.columnUplineDistributorId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorTitleColumn {
                get {
                    return this.columnDistributorTitle;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorDOBColumn {
                get {
                    return this.columnDistributorDOB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Co_DistributorTitleColumn {
                get {
                    return this.columnCo_DistributorTitle;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KeyValue11Column {
                get {
                    return this.columnKeyValue11;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Co_DistributorFirstNameColumn {
                get {
                    return this.columnCo_DistributorFirstName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Co_DistributorLastNameColumn {
                get {
                    return this.columnCo_DistributorLastName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Co_DistributorDOBColumn {
                get {
                    return this.columnCo_DistributorDOB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorAddress1Column {
                get {
                    return this.columnDistributorAddress1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorAddress2Column {
                get {
                    return this.columnDistributorAddress2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorAddress3Column {
                get {
                    return this.columnDistributorAddress3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorAddress4Column {
                get {
                    return this.columnDistributorAddress4;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorCityCodeColumn {
                get {
                    return this.columnDistributorCityCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CityNameColumn {
                get {
                    return this.columnCityName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorStateCodeColumn {
                get {
                    return this.columnDistributorStateCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn StateNameColumn {
                get {
                    return this.columnStateName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorCountryCodeColumn {
                get {
                    return this.columnDistributorCountryCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CountryNameColumn {
                get {
                    return this.columnCountryName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorPinCodeColumn {
                get {
                    return this.columnDistributorPinCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorTeleNumberColumn {
                get {
                    return this.columnDistributorTeleNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorMobNumberColumn {
                get {
                    return this.columnDistributorMobNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorFaxNumberColumn {
                get {
                    return this.columnDistributorFaxNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorEMailIDColumn {
                get {
                    return this.columnDistributorEMailID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorPANNumberColumn {
                get {
                    return this.columnDistributorPANNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorRegistrationDateColumn {
                get {
                    return this.columnDistributorRegistrationDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorBankBranchColumn {
                get {
                    return this.columnDistributorBankBranch;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorBankAccNumberColumn {
                get {
                    return this.columnDistributorBankAccNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DistributorBankNameColumn {
                get {
                    return this.columnDistributorBankName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BankIDColumn {
                get {
                    return this.columnBankID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BankNameColumn {
                get {
                    return this.columnBankName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BranchNameColumn {
                get {
                    return this.columnBranchName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FullNameColumn {
                get {
                    return this.columnFullName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SaveOnColumn {
                get {
                    return this.columnSaveOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RptDistributorDetailRow this[int index] {
                get {
                    return ((RptDistributorDetailRow)(this.Rows[index]));
                }
            }
            
            public event RptDistributorDetailRowChangeEventHandler RptDistributorDetailRowChanging;
            
            public event RptDistributorDetailRowChangeEventHandler RptDistributorDetailRowChanged;
            
            public event RptDistributorDetailRowChangeEventHandler RptDistributorDetailRowDeleting;
            
            public event RptDistributorDetailRowChangeEventHandler RptDistributorDetailRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRptDistributorDetailRow(RptDistributorDetailRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RptDistributorDetailRow AddRptDistributorDetailRow(
                        string DistributorId, 
                        string UplineDistributorId, 
                        string DistributorTitle, 
                        string DistributorDOB, 
                        string Co_DistributorTitle, 
                        string KeyValue11, 
                        string Co_DistributorFirstName, 
                        string Co_DistributorLastName, 
                        string Co_DistributorDOB, 
                        string DistributorAddress1, 
                        string DistributorAddress2, 
                        string DistributorAddress3, 
                        string DistributorAddress4, 
                        string DistributorCityCode, 
                        string CityName, 
                        string DistributorStateCode, 
                        string StateName, 
                        string DistributorCountryCode, 
                        string CountryName, 
                        string DistributorPinCode, 
                        string DistributorTeleNumber, 
                        string DistributorMobNumber, 
                        string DistributorFaxNumber, 
                        string DistributorEMailID, 
                        string DistributorPANNumber, 
                        string DistributorRegistrationDate, 
                        string DistributorBankBranch, 
                        string DistributorBankAccNumber, 
                        string DistributorBankName, 
                        string BankID, 
                        string BankName, 
                        string BranchName, 
                        string FullName, 
                        string SaveOn) {
                RptDistributorDetailRow rowRptDistributorDetailRow = ((RptDistributorDetailRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        DistributorId,
                        UplineDistributorId,
                        DistributorTitle,
                        DistributorDOB,
                        Co_DistributorTitle,
                        KeyValue11,
                        Co_DistributorFirstName,
                        Co_DistributorLastName,
                        Co_DistributorDOB,
                        DistributorAddress1,
                        DistributorAddress2,
                        DistributorAddress3,
                        DistributorAddress4,
                        DistributorCityCode,
                        CityName,
                        DistributorStateCode,
                        StateName,
                        DistributorCountryCode,
                        CountryName,
                        DistributorPinCode,
                        DistributorTeleNumber,
                        DistributorMobNumber,
                        DistributorFaxNumber,
                        DistributorEMailID,
                        DistributorPANNumber,
                        DistributorRegistrationDate,
                        DistributorBankBranch,
                        DistributorBankAccNumber,
                        DistributorBankName,
                        BankID,
                        BankName,
                        BranchName,
                        FullName,
                        SaveOn};
                rowRptDistributorDetailRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRptDistributorDetailRow);
                return rowRptDistributorDetailRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                RptDistributorDetailDataTable cln = ((RptDistributorDetailDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new RptDistributorDetailDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnDistributorId = base.Columns["DistributorId"];
                this.columnUplineDistributorId = base.Columns["UplineDistributorId"];
                this.columnDistributorTitle = base.Columns["DistributorTitle"];
                this.columnDistributorDOB = base.Columns["DistributorDOB"];
                this.columnCo_DistributorTitle = base.Columns["Co_DistributorTitle"];
                this.columnKeyValue11 = base.Columns["KeyValue11"];
                this.columnCo_DistributorFirstName = base.Columns["Co_DistributorFirstName"];
                this.columnCo_DistributorLastName = base.Columns["Co_DistributorLastName"];
                this.columnCo_DistributorDOB = base.Columns["Co_DistributorDOB"];
                this.columnDistributorAddress1 = base.Columns["DistributorAddress1"];
                this.columnDistributorAddress2 = base.Columns["DistributorAddress2"];
                this.columnDistributorAddress3 = base.Columns["DistributorAddress3"];
                this.columnDistributorAddress4 = base.Columns["DistributorAddress4"];
                this.columnDistributorCityCode = base.Columns["DistributorCityCode"];
                this.columnCityName = base.Columns["CityName"];
                this.columnDistributorStateCode = base.Columns["DistributorStateCode"];
                this.columnStateName = base.Columns["StateName"];
                this.columnDistributorCountryCode = base.Columns["DistributorCountryCode"];
                this.columnCountryName = base.Columns["CountryName"];
                this.columnDistributorPinCode = base.Columns["DistributorPinCode"];
                this.columnDistributorTeleNumber = base.Columns["DistributorTeleNumber"];
                this.columnDistributorMobNumber = base.Columns["DistributorMobNumber"];
                this.columnDistributorFaxNumber = base.Columns["DistributorFaxNumber"];
                this.columnDistributorEMailID = base.Columns["DistributorEMailID"];
                this.columnDistributorPANNumber = base.Columns["DistributorPANNumber"];
                this.columnDistributorRegistrationDate = base.Columns["DistributorRegistrationDate"];
                this.columnDistributorBankBranch = base.Columns["DistributorBankBranch"];
                this.columnDistributorBankAccNumber = base.Columns["DistributorBankAccNumber"];
                this.columnDistributorBankName = base.Columns["DistributorBankName"];
                this.columnBankID = base.Columns["BankID"];
                this.columnBankName = base.Columns["BankName"];
                this.columnBranchName = base.Columns["BranchName"];
                this.columnFullName = base.Columns["FullName"];
                this.columnSaveOn = base.Columns["SaveOn"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnDistributorId = new global::System.Data.DataColumn("DistributorId", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorId);
                this.columnUplineDistributorId = new global::System.Data.DataColumn("UplineDistributorId", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUplineDistributorId);
                this.columnDistributorTitle = new global::System.Data.DataColumn("DistributorTitle", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorTitle);
                this.columnDistributorDOB = new global::System.Data.DataColumn("DistributorDOB", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorDOB);
                this.columnCo_DistributorTitle = new global::System.Data.DataColumn("Co_DistributorTitle", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCo_DistributorTitle);
                this.columnKeyValue11 = new global::System.Data.DataColumn("KeyValue11", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKeyValue11);
                this.columnCo_DistributorFirstName = new global::System.Data.DataColumn("Co_DistributorFirstName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCo_DistributorFirstName);
                this.columnCo_DistributorLastName = new global::System.Data.DataColumn("Co_DistributorLastName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCo_DistributorLastName);
                this.columnCo_DistributorDOB = new global::System.Data.DataColumn("Co_DistributorDOB", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCo_DistributorDOB);
                this.columnDistributorAddress1 = new global::System.Data.DataColumn("DistributorAddress1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorAddress1);
                this.columnDistributorAddress2 = new global::System.Data.DataColumn("DistributorAddress2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorAddress2);
                this.columnDistributorAddress3 = new global::System.Data.DataColumn("DistributorAddress3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorAddress3);
                this.columnDistributorAddress4 = new global::System.Data.DataColumn("DistributorAddress4", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorAddress4);
                this.columnDistributorCityCode = new global::System.Data.DataColumn("DistributorCityCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorCityCode);
                this.columnCityName = new global::System.Data.DataColumn("CityName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCityName);
                this.columnDistributorStateCode = new global::System.Data.DataColumn("DistributorStateCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorStateCode);
                this.columnStateName = new global::System.Data.DataColumn("StateName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStateName);
                this.columnDistributorCountryCode = new global::System.Data.DataColumn("DistributorCountryCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorCountryCode);
                this.columnCountryName = new global::System.Data.DataColumn("CountryName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCountryName);
                this.columnDistributorPinCode = new global::System.Data.DataColumn("DistributorPinCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorPinCode);
                this.columnDistributorTeleNumber = new global::System.Data.DataColumn("DistributorTeleNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorTeleNumber);
                this.columnDistributorMobNumber = new global::System.Data.DataColumn("DistributorMobNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorMobNumber);
                this.columnDistributorFaxNumber = new global::System.Data.DataColumn("DistributorFaxNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorFaxNumber);
                this.columnDistributorEMailID = new global::System.Data.DataColumn("DistributorEMailID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorEMailID);
                this.columnDistributorPANNumber = new global::System.Data.DataColumn("DistributorPANNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorPANNumber);
                this.columnDistributorRegistrationDate = new global::System.Data.DataColumn("DistributorRegistrationDate", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorRegistrationDate);
                this.columnDistributorBankBranch = new global::System.Data.DataColumn("DistributorBankBranch", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorBankBranch);
                this.columnDistributorBankAccNumber = new global::System.Data.DataColumn("DistributorBankAccNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorBankAccNumber);
                this.columnDistributorBankName = new global::System.Data.DataColumn("DistributorBankName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistributorBankName);
                this.columnBankID = new global::System.Data.DataColumn("BankID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBankID);
                this.columnBankName = new global::System.Data.DataColumn("BankName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBankName);
                this.columnBranchName = new global::System.Data.DataColumn("BranchName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBranchName);
                this.columnFullName = new global::System.Data.DataColumn("FullName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFullName);
                this.columnSaveOn = new global::System.Data.DataColumn("SaveOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSaveOn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RptDistributorDetailRow NewRptDistributorDetailRow() {
                return ((RptDistributorDetailRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RptDistributorDetailRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(RptDistributorDetailRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RptDistributorDetailRowChanged != null)) {
                    this.RptDistributorDetailRowChanged(this, new RptDistributorDetailRowChangeEvent(((RptDistributorDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RptDistributorDetailRowChanging != null)) {
                    this.RptDistributorDetailRowChanging(this, new RptDistributorDetailRowChangeEvent(((RptDistributorDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RptDistributorDetailRowDeleted != null)) {
                    this.RptDistributorDetailRowDeleted(this, new RptDistributorDetailRowChangeEvent(((RptDistributorDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RptDistributorDetailRowDeleting != null)) {
                    this.RptDistributorDetailRowDeleting(this, new RptDistributorDetailRowChangeEvent(((RptDistributorDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRptDistributorDetailRow(RptDistributorDetailRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DistributorPanBankDetails ds = new DistributorPanBankDetails();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "RptDistributorDetailDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class RptDistributorDetailRow : global::System.Data.DataRow {
            
            private RptDistributorDetailDataTable tableRptDistributorDetail;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RptDistributorDetailRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRptDistributorDetail = ((RptDistributorDetailDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorId {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorId\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UplineDistributorId {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.UplineDistributorIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UplineDistributorId\' in table \'RptDistributorDetail\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.UplineDistributorIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorTitle {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorTitleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorTitle\' in table \'RptDistributorDetail\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorTitleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorDOB {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorDOBColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorDOB\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorDOBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Co_DistributorTitle {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.Co_DistributorTitleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Co_DistributorTitle\' in table \'RptDistributorDetail\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.Co_DistributorTitleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string KeyValue11 {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.KeyValue11Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'KeyValue11\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.KeyValue11Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Co_DistributorFirstName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.Co_DistributorFirstNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Co_DistributorFirstName\' in table \'RptDistributorDetail\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.Co_DistributorFirstNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Co_DistributorLastName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.Co_DistributorLastNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Co_DistributorLastName\' in table \'RptDistributorDetail\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.Co_DistributorLastNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Co_DistributorDOB {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.Co_DistributorDOBColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Co_DistributorDOB\' in table \'RptDistributorDetail\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.Co_DistributorDOBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorAddress1 {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorAddress1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorAddress1\' in table \'RptDistributorDetail\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorAddress1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorAddress2 {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorAddress2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorAddress2\' in table \'RptDistributorDetail\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorAddress2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorAddress3 {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorAddress3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorAddress3\' in table \'RptDistributorDetail\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorAddress3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorAddress4 {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorAddress4Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorAddress4\' in table \'RptDistributorDetail\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorAddress4Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorCityCode {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorCityCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorCityCode\' in table \'RptDistributorDetail\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorCityCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CityName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.CityNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CityName\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.CityNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorStateCode {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorStateCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorStateCode\' in table \'RptDistributorDetail\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorStateCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string StateName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.StateNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'StateName\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.StateNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorCountryCode {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorCountryCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorCountryCode\' in table \'RptDistributorDetail\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorCountryCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CountryName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.CountryNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CountryName\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.CountryNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorPinCode {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorPinCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorPinCode\' in table \'RptDistributorDetail\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorPinCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorTeleNumber {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorTeleNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorTeleNumber\' in table \'RptDistributorDetail\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorTeleNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorMobNumber {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorMobNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorMobNumber\' in table \'RptDistributorDetail\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorMobNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorFaxNumber {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorFaxNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorFaxNumber\' in table \'RptDistributorDetail\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorFaxNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorEMailID {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorEMailIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorEMailID\' in table \'RptDistributorDetail\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorEMailIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorPANNumber {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorPANNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorPANNumber\' in table \'RptDistributorDetail\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorPANNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorRegistrationDate {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorRegistrationDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorRegistrationDate\' in table \'RptDistributorDetail" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorRegistrationDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorBankBranch {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorBankBranchColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorBankBranch\' in table \'RptDistributorDetail\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorBankBranchColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorBankAccNumber {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorBankAccNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorBankAccNumber\' in table \'RptDistributorDetail\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorBankAccNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DistributorBankName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.DistributorBankNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DistributorBankName\' in table \'RptDistributorDetail\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.DistributorBankNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BankID {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.BankIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BankID\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.BankIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BankName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.BankNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BankName\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.BankNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BranchName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.BranchNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BranchName\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.BranchNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FullName {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.FullNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FullName\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.FullNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SaveOn {
                get {
                    try {
                        return ((string)(this[this.tableRptDistributorDetail.SaveOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SaveOn\' in table \'RptDistributorDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRptDistributorDetail.SaveOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorIdNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorIdNull() {
                this[this.tableRptDistributorDetail.DistributorIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUplineDistributorIdNull() {
                return this.IsNull(this.tableRptDistributorDetail.UplineDistributorIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUplineDistributorIdNull() {
                this[this.tableRptDistributorDetail.UplineDistributorIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorTitleNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorTitleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorTitleNull() {
                this[this.tableRptDistributorDetail.DistributorTitleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorDOBNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorDOBColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorDOBNull() {
                this[this.tableRptDistributorDetail.DistributorDOBColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCo_DistributorTitleNull() {
                return this.IsNull(this.tableRptDistributorDetail.Co_DistributorTitleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCo_DistributorTitleNull() {
                this[this.tableRptDistributorDetail.Co_DistributorTitleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKeyValue11Null() {
                return this.IsNull(this.tableRptDistributorDetail.KeyValue11Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKeyValue11Null() {
                this[this.tableRptDistributorDetail.KeyValue11Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCo_DistributorFirstNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.Co_DistributorFirstNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCo_DistributorFirstNameNull() {
                this[this.tableRptDistributorDetail.Co_DistributorFirstNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCo_DistributorLastNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.Co_DistributorLastNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCo_DistributorLastNameNull() {
                this[this.tableRptDistributorDetail.Co_DistributorLastNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCo_DistributorDOBNull() {
                return this.IsNull(this.tableRptDistributorDetail.Co_DistributorDOBColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCo_DistributorDOBNull() {
                this[this.tableRptDistributorDetail.Co_DistributorDOBColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorAddress1Null() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorAddress1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorAddress1Null() {
                this[this.tableRptDistributorDetail.DistributorAddress1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorAddress2Null() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorAddress2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorAddress2Null() {
                this[this.tableRptDistributorDetail.DistributorAddress2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorAddress3Null() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorAddress3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorAddress3Null() {
                this[this.tableRptDistributorDetail.DistributorAddress3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorAddress4Null() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorAddress4Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorAddress4Null() {
                this[this.tableRptDistributorDetail.DistributorAddress4Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorCityCodeNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorCityCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorCityCodeNull() {
                this[this.tableRptDistributorDetail.DistributorCityCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCityNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.CityNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCityNameNull() {
                this[this.tableRptDistributorDetail.CityNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorStateCodeNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorStateCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorStateCodeNull() {
                this[this.tableRptDistributorDetail.DistributorStateCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsStateNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.StateNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetStateNameNull() {
                this[this.tableRptDistributorDetail.StateNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorCountryCodeNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorCountryCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorCountryCodeNull() {
                this[this.tableRptDistributorDetail.DistributorCountryCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCountryNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.CountryNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCountryNameNull() {
                this[this.tableRptDistributorDetail.CountryNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorPinCodeNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorPinCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorPinCodeNull() {
                this[this.tableRptDistributorDetail.DistributorPinCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorTeleNumberNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorTeleNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorTeleNumberNull() {
                this[this.tableRptDistributorDetail.DistributorTeleNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorMobNumberNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorMobNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorMobNumberNull() {
                this[this.tableRptDistributorDetail.DistributorMobNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorFaxNumberNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorFaxNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorFaxNumberNull() {
                this[this.tableRptDistributorDetail.DistributorFaxNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorEMailIDNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorEMailIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorEMailIDNull() {
                this[this.tableRptDistributorDetail.DistributorEMailIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorPANNumberNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorPANNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorPANNumberNull() {
                this[this.tableRptDistributorDetail.DistributorPANNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorRegistrationDateNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorRegistrationDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorRegistrationDateNull() {
                this[this.tableRptDistributorDetail.DistributorRegistrationDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorBankBranchNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorBankBranchColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorBankBranchNull() {
                this[this.tableRptDistributorDetail.DistributorBankBranchColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorBankAccNumberNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorBankAccNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorBankAccNumberNull() {
                this[this.tableRptDistributorDetail.DistributorBankAccNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDistributorBankNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.DistributorBankNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDistributorBankNameNull() {
                this[this.tableRptDistributorDetail.DistributorBankNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBankIDNull() {
                return this.IsNull(this.tableRptDistributorDetail.BankIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBankIDNull() {
                this[this.tableRptDistributorDetail.BankIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBankNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.BankNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBankNameNull() {
                this[this.tableRptDistributorDetail.BankNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBranchNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.BranchNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBranchNameNull() {
                this[this.tableRptDistributorDetail.BranchNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFullNameNull() {
                return this.IsNull(this.tableRptDistributorDetail.FullNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFullNameNull() {
                this[this.tableRptDistributorDetail.FullNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSaveOnNull() {
                return this.IsNull(this.tableRptDistributorDetail.SaveOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSaveOnNull() {
                this[this.tableRptDistributorDetail.SaveOnColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class RptDistributorDetailRowChangeEvent : global::System.EventArgs {
            
            private RptDistributorDetailRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RptDistributorDetailRowChangeEvent(RptDistributorDetailRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RptDistributorDetailRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591